## numpy基本属性

In [2]:
from tkinter import N
import numpy as np
# 创建矩阵
arr = np.array([[1,2,2],
                [2,3,4]])
print('arr:\n',arr,'\n')

# 创建矩阵时可以自己定义数据类型
arr1 = np.array([[1,2,2],
                [2,3,4]],dtype=np.int32)
print('dtype:',arr1.dtype,'\n')   

# 全零矩阵
arr2 = np.zeros((2,2))
print('all zeros:\n',arr2,'\n')
# 全一矩阵
arr3 = np.ones((2,3),dtype=np.int32)
print('all one:\n',arr3)
# 空矩阵
arr4 = np.empty((2,3))
print('\nempty:\n',arr4)
# 有序数列
arr5 = np.arange(2,10,2).reshape((2,2))
print('\norder:\n',arr5)
# 给定区间和数量
arr6 = np.linspace(1,10,5)
print('\ninspace:',arr6)

arr:
 [[1 2 2]
 [2 3 4]] 

dtype: int32 

all zeros:
 [[0. 0.]
 [0. 0.]] 

all one:
 [[1 1 1]
 [1 1 1]]

empty:
 [[8.96030866e-312 8.96030863e-312 8.96030866e-312]
 [8.96030866e-312 8.96030866e-312 8.96030866e-312]]

order:
 [[2 4]
 [6 8]]

inspace: [ 1.    3.25  5.5   7.75 10.  ]


In [3]:
# 矩阵的维度
print('number of dim: ',arr.ndim)
# 矩阵的形状
print('shape: ',arr.shape)
# 矩阵的元素个数
print('size: ',arr.size)

number of dim:  2
shape:  (2, 3)
size:  6


## 矩阵运算

In [4]:
a = np.array([1,2,3,4])
b = np.array([0,2,4,6])

# 矩阵相加
print('Add:',a+b)
# 矩阵相减
print('Subtract:',a-b)

Add: [ 1  4  7 10]
Subtract: [ 1  0 -1 -2]


In [5]:
# 乘方
print('power:',a**2)

# 矩阵元素相乘
a1 = a.reshape((2,2))
b1 = b.reshape((2,2))
c = a1*b1
print('\nmultiply one by one:\n',c)

# 矩阵相乘
c_dot = np.dot(a1,b1)
print('\nmultiply matric by matric:\n',c_dot)

power: [ 1  4  9 16]

multiply one by one:
 [[ 0  4]
 [12 24]]

multiply matric by matric:
 [[ 8 14]
 [16 30]]


In [6]:
# 随机生成0~1之间元素的矩阵
aa = np.random.random((2,3))
print(aa)

# axis = 1,  按行
# axis = 0,  按列
# 矩阵中所有元素求和
print('\nsum all:',np.sum(aa,axis=1))
# 矩阵中最大的元素
print('\nmax of Matric:',np.max(aa,axis=0))
# 矩阵中最小的元素
print('\nmin of Matric:',np.min(aa))

[[0.04874953 0.69317736 0.69172806]
 [0.68420425 0.41983663 0.74675757]]

sum all: [1.43365495 1.85079845]

max of Matric: [0.68420425 0.69317736 0.74675757]

min of Matric: 0.04874952621219597


In [7]:
a = np.arange(1,9).reshape(2,4)
print(a)
# 最小值的索引
print('index of min:',a.argmin())
# 最大值的索引
print('index of max:',np.argmax(a))
# 平均值的索引
print('index of mean:',a.mean())

[[1 2 3 4]
 [5 6 7 8]]
index of min: 0
index of max: 7
index of mean: 4.5


In [8]:
# 矩阵的转置
print('Transpose of Matric:\n',a.transpose())
print('Transpose of Matric:\n',np.transpose(a))
print('Transpose of Matric:\n',a.T)

Transpose of Matric:
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]
Transpose of Matric:
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]
Transpose of Matric:
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [9]:
# 切割替换矩阵元素
# 指定最小和最大的元素，保留中间元素
print('clip:\n',np.clip(a,3,6))

clip:
 [[3 3 3 4]
 [5 6 6 6]]


## 索引

In [17]:
# 矩阵索引
print(a)
print('first item:',a[0][0])
print('\nfirst row:\n',a[0])
print('\nfirst column:\n',a.T[0])
print('\nsecond column:\n',a[:,1])

[[1 2 3 4]
 [5 6 7 8]]
first item: 1

first row:
 [1 2 3 4]

first column:
 [1 5]

second column:
 [2 6]


In [27]:
# 遍历所有行
print('遍历所有行:')
for row in a:
    print(row)

# 遍历所有列
print('\n遍历所有列:')
for column in a.T:
    print(column)

# 遍历所有元素
print('\n遍历所有元素:')
for item in a.flat:
    print(item,end = " ")

遍历所有行:
[1 2 3 4]
[5 6 7 8]

遍历所有列:
[1 5]
[2 6]
[3 7]
[4 8]

遍历所有元素:
1 2 3 4 5 6 7 8 

In [49]:
# 合并矩阵
A = np.ones((1,3),dtype=int)
B = 2*np.ones((1,3))
print('A:\n',A)
print('B:\n',B)

# 上下合并（vertical stack）
C = np.vstack((A,B))
print('\nvertical stack:\n',C)

# 左右合并（horizontal stack）
D = np.hstack((A,B))
print('\nhorizontal stack:\n',D)


A:
 [[1 1 1]]
B:
 [[2. 2. 2.]]

vertical stack:
 [[1. 1. 1.]
 [2. 2. 2.]]

horizontal stack:
 [[1. 1. 1. 2. 2. 2.]]
