# Numpy 中一些函数的用法

### Numpy.random 模块
总的来说分为四种模块，四个功能
1. 简单随机数： 产生简单的随机数据，可以是任何维度 
2. 排列：将所给对象随机排列 
3. 分布：产生指定分布的数据，如高斯分布等 
4. 生成器：种随机数种子，根据同一种子产生的随机数是相同的 

#### 1.生成器

![jupyter](./image/random_seed.png)

#### 2.简单随机数

![jupyter](./image/random_randn.jpg)

#### 3.分布

![jupyter](./image/random_beta.jpg)

#### 4.排列

![jupyter](./image/random_shuffle.jpg)

In [3]:
# 正态分布
import numpy as np
rand_data = np.random.randint(1,10,(3,4))
print(rand_data)
np.random.shuffle(rand_data)
print('\n',rand_data)

[[8 1 9 3]
 [7 8 8 5]
 [7 6 3 7]]

 [[7 8 8 5]
 [8 1 9 3]
 [7 6 3 7]]
